apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: ip_client
          matcherRegex: 'ip_client="(\d+\.\d+\.\d+\.\d+)"'
          url: 'http://loki:3100/loki/api/v1/query?query={ip_client="$1"}'
